#!/bin/sh
'''exec' C:/Users/ARTHUR/S52/S53/BBA_D01_IDENTITE/aufilduboamp_docs/afdb_docs_env/bin/python "$0" "$@"
' '''
# -*- coding: utf-8 -*-
import re
import sys
from myst_parser.cli import print_anchors
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(print_anchors())
